package com.example.mvvmKotlinJetpackCompose.util


const val PREF_NAME = "Liquor_coin_pref"
const val PREF_KEY_USER_LOGGED_IN_MODE = "PREF_KEY_USER_LOGGED_IN_MODE"
const val PREF_KEY_CURRENT_USER_ID = "PREF_KEY_CURRENT_USER_ID"
const val PREF_KEY_CURRENT_USER_NAME = "PREF_KEY_CURRENT_USER_NAME"
const val PREF_KEY_CURRENT_USER_EMAIL = "PREF_KEY_CURRENT_USER_EMAIL"
const val PREF_KEY_CURRENT_USER_PROFILE_PIC_URL = "PREF_KEY_CURRENT_USER_PROFILE_PIC_URL"
const val PREF_KEY_ACCESS_TOKEN = "PREF_KEY_ACCESS_TOKEN"
const val NULL_INDEX = "-1"


enum class LoggedInMode(val type: Int) {
    LOGGED_IN_MODE_LOGGED_OUT(0),
    LOGGED_IN_MODE_GOOGLE(1),
    LOGGED_IN_MODE_FB(2),
    LOGGED_IN_MODE_SERVER(3);

}